{% set name = "sunkit-image" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sunkit_image-{{ version }}.tar.gz
  sha256: bae1ccd22421eb9166deb3b122975f1cb0becb5471543441a76279e0db89f1f3

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
    - extension-helpers
  run:
    - python >={{ python_min }}
    - sunpy >=5.0.0
    - scikit-image >=0.18.0

test:
  requires:
    - pytest-astropy
    - pytest-doctestplus
    - pytest-mock
    - dask
    - python {{ python_min }}
  imports:
    - sunkit_image
    - sunkit_image.enhance
    - sunkit_image.radial
    - sunkit_image.time_lag
    - sunkit_image.trace
    - sunkit_image.utils
  commands:
    - python -m pytest -vvv --pyargs sunkit_image

about:
  home: https://github.com/sunpy/sunkit-image
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A image processing toolbox for Solar Physics
  description: |
    sunkit-image is a community-developed, free and open-source solar data image analysis environment for Python
  doc_url: https://docs.sunpy.org/projects/sunkit-image/
  dev_url: https://github.com/sunpy/sunkit-image

extra:
  recipe-maintainers:
    - cadair
    - nabobalis
    - wtbarnes
